services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./hotel_bookings.db
    volumes:
      # Mount data directory to persist database
      - ./data:/app/data
      # Optionally mount database file directly
      - ./hotel_bookings.db:/app/hotel_bookings.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
